export * from "./home/Home";
export * from "./bookDetail/Bookdeatil";
export * from "./footer/Footer";
export * from "./hedaer/Hedaer";
export * from "./loading/Loading";
export * from "./books/Books";
export * from "./search/Search";
export * from "./menu/Menu";
export * from "./404Page/Page404";
